defaults: &defaults
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password: 
 
development:
  database: bantuin
  <<: *defaults
 
test:
  database: bantuin_test
  <<: *defaults
 
production:
  database: bantuin_development
  <<: *defaults
