defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: lophyounee86
 
development:
  database: bantuin_development
  <<: *defaults
 
test:
  database: bantuin_test
  <<: *defaults
 
production:
  database: bantuin_development
  <<: *defaults
